apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-ci-agent
  namespace: jenkins
  labels:
    app.kubernetes.io/name: jenkins-ci-agent
    app.kubernetes.io/component: ci-agent
  annotations:
    eks.amazonaws.com/role-arn: "${JENKINS_CI_ROLE_ARN}"
automountServiceAccountToken: true
