apiVersion: v1
kind: Secret
metadata:
  name: devops-secret
  namespace: devops-app
type: Opaque
stringData:
  DB_HOST: "your-rds-endpoint-here"
  DB_NAME: "devopsdb"
  DB_USER: "postgres"
  DB_PASSWORD: "replace-with-real-password"
