apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "worker.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.metrics.servicePort }}
      targetPort: metrics

