controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: "2.568.1-jdk21"
    pullPolicy: IfNotPresent

  replicas: 1

  numExecutors: 0
  executorMode: EXCLUSIVE
  disableRememberMe: true

  admin:
    username: admin
    createSecret: true

  serviceEnabled: true
  serviceType: ClusterIP
  servicePort: 8080
  targetPort: 8080

  resources:
    requests:
      cpu: 250m
      memory: 768Mi
    limits:
      cpu: "1"
      memory: 1536Mi

  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  podSecurityContextOverride:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

  healthProbes: true

  probes:
    startupProbe:
      failureThreshold: 30
      periodSeconds: 10
      timeoutSeconds: 5

    livenessProbe:
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 5

    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      timeoutSeconds: 5

  installPlugins:
    - kubernetes:4540.v612369217f87
    - workflow-aggregator:608.v67378e9d3db_1
    - git:5.10.1
    - configuration-as-code:2111.v475308a_6c93b_
    - job-dsl:3654.vdf58f53e2d15
    - github:1.47.0
    - junit:1416.vd753e036de5e
    - ws-cleanup:0.49
    - credentials-binding:728.v902a_273b_8947
    - plain-credentials:199.v9f8e1f741799

  installLatestPlugins: false
  installLatestSpecifiedPlugins: false
  initializeOnce: true
  overwritePlugins: false
  overwritePluginsFromImage: true

  additionalExistingSecrets:
    - name: jenkins-backend-values
      keyName: backend-values-base64

  JCasC:
    defaultConfig: true
    overwriteConfiguration: false

    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
          - id: "${chart-admin-username}"
            name: "Jenkins Admin"
            password: "${chart-admin-password}"

    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false

  sidecars:
    configAutoReload:
      enabled: true
      searchNamespace: jenkins

      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi

persistence:
  enabled: true
  storageClass: jenkins-ebs
  accessMode: ReadWriteOnce
  size: 8Gi

rbac:
  create: true
  readSecrets: false

serviceAccount:
  create: true
  name: jenkins-controller
  automountServiceAccountToken: true

serviceAccountAgent:
  create: false

networkPolicy:
  enabled: false