jenkins:
  systemMessage: |
    DevOps on AWS - Task 4
    Jenkins is configured and managed as code.
    CI and CD run on dynamic Kubernetes agent Pods.

  numExecutors: 0
  mode: EXCLUSIVE
  scmCheckoutRetryCount: 2
  disableRememberMe: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - file:
              scope: GLOBAL
              id: backend-values-local
              fileName: values.local.yaml
              secretBytes: "${jenkins-backend-values-backend-values-base64}"
              description: Backend Helm values for the CD Pipeline

jobs:
  - file: /var/jenkins_home/casc_configs/jobs.groovy